apiVersion: v1
kind: ConfigMap
metadata:
  name: huly-config
data:
  ACCOUNTS_URL: 'http://account.${DOMAIN}/'
  COLLABORATOR_URL: 'ws://collaborator.${DOMAIN}/'
  FRONT_URL: 'http://${DOMAIN}'
  REKONI_URL: 'http://rekoni.${DOMAIN}/'
  STATS_URL: 'http://stats.${DOMAIN}/'
  TRANSACTOR_URL: 'ws://transactor;ws://transactor.${DOMAIN}/'
  MINIO_ENDPOINT: 'minio'
  MONGO_URL: 'mongodb://mongodb:27017'
  ELASTIC_URL: 'http://elastic:9200'
  ELASTIC_INDEX_NAME: 'huly_storage_index'
