apiVersion: v1
kind: ConfigMap
metadata:
  name: huly-config
data:
  ACCOUNTS_URL: 'http${TLS:+s}://account.${DOMAIN}/'
  COLLABORATOR_URL: 'ws${TLS:+s}://collaborator.${DOMAIN}/'
  FRONT_URL: 'http${TLS:+s}://${DOMAIN}'
  REKONI_URL: 'http${TLS:+s}://rekoni.${DOMAIN}/'
  STATS_URL: 'http${TLS:+s}://stats.${DOMAIN}/'
  TRANSACTOR_URL: 'ws${TLS:+s}://transactor;ws${TLS:+s}://transactor.${DOMAIN}/'
  MINIO_ENDPOINT: 'minio'
  MONGO_URL: 'mongodb://mongodb:27017'
  ELASTIC_URL: 'http://elastic:9200'
  ELASTIC_INDEX_NAME: 'huly_storage_index'
